export const ERR_FORBIDDEN = "RB_ERR_FORBIDDEN";
export const ERR_INVALID_RESOURCE = "RB_ERR_INVALID_RESOURCE";
export const ERR_INVALID_AUTH_PROVIDER = "RB_ERR_INVALID_AUTH_PROVIDER";
export const ERR_INVALID_RESOURCE_DATA_PROVIDER =
  "RB_ERR_INVALID_RESOURCE_DATA_PROVIDER";
export const ERR_INVALID_ACTION = "RB_ERR_INVALID_ACTION";
export const ERR_NOT_IMPLEMENTED = "RB_ERR_NOT_IMPLEMENTED";
export const ERR_UNAUTHORIZED = "RB_ERR_UNAUTHORIZED";

export default {
  ERR_FORBIDDEN,
  ERR_INVALID_RESOURCE,
  ERR_INVALID_AUTH_PROVIDER,
  ERR_INVALID_RESOURCE_DATA_PROVIDER,
  ERR_INVALID_ACTION,
  ERR_NOT_IMPLEMENTED,
  ERR_UNAUTHORIZED,
};
