export const ERR_NOT_IMPLEMENTED = "RB_ERR_NOT_IMPLEMENTED";
export const ERR_MISSING_RESOURCE_NAME = "RB_ERR_MISSING_RESOURCE_NAME";
export const ERR_MISSING_RESOURCE_DATA_PROVIDER =
  "ERR_MISSING_RESOURCE_DATA_PROVIDER";
export const ERR_INVALID_RESOURCE_DATA_PROVIDER =
  "ERR_INVALID_RESOURCE_DATA_PROVIDER";

export default {
  ERR_NOT_IMPLEMENTED,
  ERR_MISSING_RESOURCE_NAME,
  ERR_MISSING_RESOURCE_DATA_PROVIDER,
  ERR_INVALID_RESOURCE_DATA_PROVIDER,
};
